//! Gate C: the icepool oracle (spec 0032 S4).
//!
//! `fixtures/oracle_gen.rs` is GENERATED by `tools/gen_oracle.py` from the
//! real icepool (v2.2.2 @ 33e7e650, `/home/jbassin/icepool`) alongside the
//! human-readable `fixtures/oracle.json`; regenerate with
//! `uv run --no-project python tools/gen_oracle.py`. The generated-Rust
//! route is used because serde is not a crate dependency — the fixture is
//! consumed via `include!`, no JSON parsing.
//!
//! Comparison convention: both sides are `simplify()`d (the Python side
//! dumps `die.simplify()`, this side simplifies before comparing), so
//! denominator-normalization differences between the two constructions
//! (e.g. icepool's explode denominators vs our minimal weighted-lcm
//! mixtures) cancel exactly. Weights are compared as exact integers.
//! Bool outcomes are encoded as 0/1 on both sides.

use weal_engine::dist::{
    Budget, Dist, DistError, KeepTuple, Weight, combine, explode, mix, reroll_face, reroll_faces,
    successes, sum_pool,
};

/// One generated oracle case.
pub struct OracleCase {
    pub name: &'static str,
    pub build: fn(&mut Budget) -> Result<Dist<i64>, DistError>,
    pub expected_den: &'static str,
    pub expected: &'static [(i64, &'static str)],
}

// Helpers the generated construction expressions call.

fn d(n: i64) -> Dist<i64> {
    Dist::uniform((1..=n).collect(), &Budget::default()).unwrap()
}

fn wd(pairs: &[(i64, u128)]) -> Dist<i64> {
    Dist::weighted(
        pairs
            .iter()
            .map(|(f, w)| (*f, Weight::from_u128(*w)))
            .collect(),
        &Budget::default(),
    )
    .unwrap()
}

fn constant(f: i64) -> Dist<i64> {
    Dist::constant(f)
}

include!("../fixtures/oracle_gen.rs");

#[test]
fn oracle_has_at_least_25_cases() {
    assert!(CASES.len() >= 25, "only {} oracle cases", CASES.len());
}

#[test]
fn oracle_exact_weight_equality() {
    let mut failures: Vec<String> = Vec::new();
    for case in CASES {
        let mut budget = Budget::default();
        let dist = match (case.build)(&mut budget) {
            Ok(d) => d.simplify(),
            Err(e) => {
                failures.push(format!("{}: build failed: {e}", case.name));
                continue;
            }
        };
        let want_den = Weight::from_decimal_str(case.expected_den).unwrap();
        if dist.denominator() != &want_den {
            failures.push(format!(
                "{}: denominator {} != expected {}",
                case.name,
                dist.denominator(),
                want_den
            ));
        }
        if dist.support_len() != case.expected.len() {
            failures.push(format!(
                "{}: support size {} != expected {}",
                case.name,
                dist.support_len(),
                case.expected.len()
            ));
        }
        for (outcome, weight_str) in case.expected {
            let want = Weight::from_decimal_str(weight_str).unwrap();
            let got = dist.weight_of(outcome);
            if got != want {
                failures.push(format!(
                    "{}: weight of {outcome} is {got}, expected {want}",
                    case.name
                ));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} oracle mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
