import { describe, expect, test } from "vitest";
import { SCHEMA, TABLES } from "./schema";

describe("SCHEMA", () => {
  test("creates all nine library tables idempotently", () => {
    for (const t of TABLES) {
      expect(SCHEMA).toContain(`create table if not exists ${t} `);
    }
  });

  test("folds in the v2 tags.color column", () => {
    expect(SCHEMA).toMatch(/create table if not exists tags[\s\S]*?\bcolor\s+text/);
  });

  test("uses generated-by-default identity so the migrator can preserve IDs", () => {
    expect(SCHEMA).toContain("generated by default as identity");
    expect(SCHEMA).not.toContain("generated always as identity");
  });

  test("preserves the CHECK constraints and FK cascade actions", () => {
    expect(SCHEMA).toContain("check (status in ('ready', 'downloading', 'error'))");
    expect(SCHEMA).toContain("references tracks(id)    on delete cascade");
    expect(SCHEMA).toContain("references collections(id) on delete set null");
  });
});
