/**
 * The orator music-library schema on **Postgres** (Decision F) — the port of
 * faerrin `pkg/lark/src/db/schema.ts`'s `bun:sqlite` migrations (the v1 initial
 * schema + the v2 `tags.color` column, folded in).
 *
 * astra starts fresh on Postgres, so there's no `_migrations` ledger to carry
 * (weal-bot's precedent): one idempotent `create table if not exists` block,
 * safe to run on every boot via `LibraryStore.ensureSchema()`.
 *
 * Notes on the SQLite→PG translation:
 *  - `INTEGER PRIMARY KEY AUTOINCREMENT` → `integer generated by default as identity`
 *    (by-default, not always, so the slice-6 migrator can insert explicit IDs to
 *    preserve the load-bearing collection/track FKs).
 *  - `datetime('now')` → `now()`; text timestamps → `timestamptz`.
 *  - `REAL` → `double precision`; `shuffle`/booleans stay `integer` (0/1) to keep
 *    lark's row shapes byte-identical (no boolean-mapping churn).
 *  - `CHECK (… IN (…))` constraints and the FK ON DELETE actions carry over verbatim.
 */
export const SCHEMA = /* sql */ `
create table if not exists collections (
  id           integer     generated by default as identity primary key,
  name         text        not null,
  slug         text        not null unique,
  ip_or_game   text,
  source_type  text        not null default 'manual'
               check (source_type in ('manual', 'youtube_playlist')),
  source_url   text,
  cover_url    text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table if not exists tracks (
  id              integer     generated by default as identity primary key,
  collection_id   integer     references collections(id) on delete set null,
  title           text        not null,
  original_title  text        not null,
  source_type     text        not null check (source_type in ('upload', 'youtube')),
  source_url      text,
  source_video_id text,
  file_path       text,
  format          text,
  duration_ms     integer,
  file_size       bigint,
  loudness_lufs   double precision,
  status          text        not null default 'ready'
                  check (status in ('ready', 'downloading', 'error')),
  error           text,
  added_at        timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists idx_tracks_collection on tracks(collection_id);
create index if not exists idx_tracks_video      on tracks(source_video_id);

create table if not exists tags (
  id         integer     generated by default as identity primary key,
  name       text        not null unique,
  category   text,
  color      text,
  created_at timestamptz not null default now()
);

create table if not exists track_tags (
  track_id integer not null references tracks(id) on delete cascade,
  tag_id   integer not null references tags(id)   on delete cascade,
  primary key (track_id, tag_id)
);
create index if not exists idx_track_tags_tag on track_tags(tag_id);

create table if not exists playlists (
  id         integer     generated by default as identity primary key,
  name       text        not null,
  loop_mode  text        not null default 'none'
             check (loop_mode in ('none', 'track', 'playlist')),
  shuffle    integer     not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists playlist_items (
  id          integer generated by default as identity primary key,
  playlist_id integer not null references playlists(id) on delete cascade,
  track_id    integer not null references tracks(id)    on delete cascade,
  position    integer not null
);
create index if not exists idx_playlist_items_playlist on playlist_items(playlist_id, position);

create table if not exists download_jobs (
  id              integer     generated by default as identity primary key,
  type            text        not null check (type in ('single', 'playlist')),
  source_url      text        not null,
  title           text,
  collection_id   integer     references collections(id) on delete set null,
  status          text        not null default 'queued'
                  check (status in ('queued', 'running', 'done', 'error', 'partial')),
  total_items     integer     not null default 0,
  completed_items integer     not null default 0,
  error           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists download_job_items (
  id           integer          generated by default as identity primary key,
  job_id       integer          not null references download_jobs(id) on delete cascade,
  video_id     text             not null,
  title        text             not null,
  position     integer          not null,
  status       text             not null default 'queued'
               check (status in ('queued', 'downloading', 'done', 'error')),
  progress_pct double precision not null default 0,
  error        text,
  track_id     integer          references tracks(id) on delete set null
);
create index if not exists idx_job_items_job on download_job_items(job_id, position);

create table if not exists api_keys (
  id           integer     generated by default as identity primary key,
  user_id      text        not null,
  name         text        not null,
  key_hash     text        not null unique,
  key_prefix   text        not null,
  created_at   timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at   timestamptz
);
create index if not exists idx_api_keys_user on api_keys(user_id);
`;

/** The nine tables the schema must create (used by the structural test + docs). */
export const TABLES = [
  "collections",
  "tracks",
  "tags",
  "track_tags",
  "playlists",
  "playlist_items",
  "download_jobs",
  "download_job_items",
  "api_keys",
] as const;
