"""``assay`` console script — extract / fit / score.

    uv run assay extract [--data-root PATH]   # features table → out/features.json
    uv run assay fit [--data-root PATH]       # fitted params + point tables → results/
    uv run assay score --spell PATH           # score one homebrew spell JSON

Telemetry (standing principle): ``init_telemetry`` wraps every subcommand, a
root span per invocation, ``shutdown()`` in ``finally`` (the short-lived-process
pattern — see ``libs/py/observe``). Offline runs (no SigNoz reachable) still
work: OTLP export failures are swallowed by the exporter, never fatal here.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from astra_observe import get_tracer, init_telemetry, shutdown

from . import report
from .extract import (
    ExtractResult,
    SkipRecord,
    SpellFeatures,
    extract_all,
    extract_spell,
    load_spell_json,
)
from .model import DesignMatrix, FitResult, build_design_matrix, fit_ols, predict_log_ev
from .snapshot import SnapshotNotFoundError, resolve_snapshot

APP_ROOT = Path(__file__).resolve().parents[2]  # src/astra_assay/cli.py -> apps/assay
OUT_DIR = APP_ROOT / "out"
RESULTS_DIR = APP_ROOT / "results"
FEATURES_PATH = OUT_DIR / "features.json"
FITTED_PARAMS_PATH = RESULTS_DIR / "fitted-params.json"
POINT_TABLES_PATH = RESULTS_DIR / "point-tables.md"
POWER_LEDGER_PATH = RESULTS_DIR / "power-ledger.md"
VALIDATION_PATH = RESULTS_DIR / "validation.md"

_tracer = get_tracer("astra.assay")


def _run_extract(data_root: str | None) -> ExtractResult:
    paths = resolve_snapshot(data_root)
    return extract_all(paths.spells_dir)


def cmd_extract(args: argparse.Namespace) -> None:
    with _tracer.start_as_current_span("assay.extract") as span:
        result = _run_extract(args.data_root)
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        FEATURES_PATH.write_text(
            json.dumps(result.model_dump(mode="json"), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        span.set_attribute("assay.extract.rows", len(result.rows))
        span.set_attribute("assay.extract.skipped", len(result.skipped))
        print(
            f"assay extract: {len(result.rows)} rows, {len(result.skipped)} skipped "
            f"-> {FEATURES_PATH}"
        )


def _fit_population(rows: list[SpellFeatures], *, cantrip: bool) -> tuple[DesignMatrix, FitResult]:
    pop = [r for r in rows if r.is_cantrip == cantrip]
    dm = build_design_matrix(pop, include_rank_ladder=not cantrip)
    return dm, fit_ols(dm)


def _fit_result_to_json(fit: FitResult, *, include_rank_ladder: bool) -> dict:
    return {
        "include_rank_ladder": include_rank_ladder,
        "columns": fit.columns,
        "coefficients": fit.coefficients,
        "n_obs": fit.n_obs,
        "n_params": fit.n_params,
        "r_squared": fit.r_squared,
        "rank_slope": fit.rank_slope,
        # JSON object keys are strings; rank is re-int()'d on load (cmd_score).
        "rank_slopes": {str(rank): slope for rank, slope in fit.rank_slopes.items()},
    }


def cmd_fit(args: argparse.Namespace) -> None:
    with _tracer.start_as_current_span("assay.fit") as span:
        extract_result = _run_extract(args.data_root)
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        FEATURES_PATH.write_text(
            json.dumps(extract_result.model_dump(mode="json"), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

        main_dm, main_fit = _fit_population(extract_result.rows, cantrip=False)
        cantrip_dm, cantrip_fit = _fit_population(extract_result.rows, cantrip=True)
        span.set_attribute("assay.fit.main.n_obs", main_fit.n_obs)
        span.set_attribute("assay.fit.cantrip.n_obs", cantrip_fit.n_obs)
        span.set_attribute("assay.fit.main.r_squared", main_fit.r_squared)

        RESULTS_DIR.mkdir(parents=True, exist_ok=True)
        params = {
            "main": _fit_result_to_json(main_fit, include_rank_ladder=True),
            "cantrip": _fit_result_to_json(cantrip_fit, include_rank_ladder=False),
        }
        FITTED_PARAMS_PATH.write_text(
            json.dumps(params, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )

        _write_point_tables(main_fit, cantrip_fit)
        _write_power_ledger(main_fit, cantrip_fit)
        main_rows = [r for r in extract_result.rows if not r.is_cantrip]
        _write_validation(main_rows, main_fit, cantrip_fit, extract_result.skipped)

        print(
            f"assay fit: main n={main_fit.n_obs} R2={main_fit.r_squared:.3f}  "
            f"cantrip n={cantrip_fit.n_obs} R2={cantrip_fit.r_squared:.3f} -> {RESULTS_DIR}"
        )


def _write_point_tables(main_fit: FitResult, cantrip_fit: FitResult) -> None:
    lines = ["# assay — damage-budget point tables (round 1)", ""]
    lines.append("Generated by `uv run assay fit`. See the design doc for methodology:")
    lines.append("`thoughts/shared/research/2026-07-19-assay-spell-power-0030-thoughts.md`.")
    lines.append("")
    lines.append("## Damage budget by rank (non-cantrip)")
    lines.append("")
    lines.append("| Rank | Fitted EV | Rounded budget | Community 7×rank | GM Core anchor |")
    lines.append("|---|---|---|---|---|")
    for row in report.rank_ladder_table(main_fit):
        anchor = f"{row.gm_core_anchor:.0f}" if row.gm_core_anchor is not None else "—"
        lines.append(
            f"| {row.rank} | {row.fitted_ev:.2f} | {row.rounded_budget:.1f} | "
            f"{row.community_7x_rank:.0f} | {anchor} |"
        )
    lines.append("")
    lines.append("## Facet multipliers (non-cantrip fit)")
    lines.append("")
    lines.append("| Facet | Multiplier | Rounded (clean fraction) |")
    lines.append("|---|---|---|")
    for f in report.facet_multiplier_table(main_fit):
        lines.append(f"| {f.name} | ×{f.multiplier:.3f} | ×{f.rounded:.3f} |")
    lines.append("")
    lines.append("## Cantrip fit (separate curve, rank-1-only population)")
    lines.append("")
    intercept = math.exp(cantrip_fit.coefficients.get("intercept", 0.0))
    lines.append(
        f"Baseline cantrip EV (all riders off): **{intercept:.2f}** "
        f"(n={cantrip_fit.n_obs}, R²={cantrip_fit.r_squared:.3f})"
    )
    lines.append("")
    lines.append("| Facet | Multiplier | Rounded (clean fraction) |")
    lines.append("|---|---|---|")
    for f in report.facet_multiplier_table(cantrip_fit):
        lines.append(f"| {f.name} | ×{f.multiplier:.3f} | ×{f.rounded:.3f} |")
    lines.append("")
    POINT_TABLES_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_power_ledger(main_fit: FitResult, cantrip_fit: FitResult) -> None:
    lines = ["# assay — per-spell power ledger (round 1)", ""]
    for label, fit, residual_col in (
        ("Non-cantrip", main_fit, "Residual (rank-equiv)"),
        ("Cantrip", cantrip_fit, "Residual (log EV — no rank ladder to divide by)"),
    ):
        ledger = report.power_ledger(fit)
        lines.append(f"## {label} (n={len(ledger)}, sorted hottest → coldest)")
        lines.append("")
        lines.append(f"| Spell | Rank | EV | Predicted | {residual_col} |")
        lines.append("|---|---|---|---|---|")
        top = ledger[:10]
        bottom = ledger[-10:] if len(ledger) > 10 else []
        for row in top:
            lines.append(
                f"| {row.name} | {row.rank} | {row.ev:.1f} | {row.predicted_ev:.1f} | "
                f"{row.residual_rank_equiv:+.2f} |"
            )
        if bottom:
            lines.append("| … | | | | |")
            for row in bottom:
                lines.append(
                    f"| {row.name} | {row.rank} | {row.ev:.1f} | {row.predicted_ev:.1f} | "
                    f"{row.residual_rank_equiv:+.2f} |"
                )
        lines.append("")
        lines.append(
            f"<details><summary>Full {label.lower()} ledger ({len(ledger)} spells)</summary>"
        )
        lines.append("")
        lines.append(f"| Spell | Rank | EV | Predicted | {residual_col} |")
        lines.append("|---|---|---|---|---|")
        for row in ledger:
            lines.append(
                f"| {row.name} | {row.rank} | {row.ev:.1f} | {row.predicted_ev:.1f} | "
                f"{row.residual_rank_equiv:+.2f} |"
            )
        lines.append("")
        lines.append("</details>")
        lines.append("")
    POWER_LEDGER_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_validation(
    main_rows: list[SpellFeatures],
    main_fit: FitResult,
    cantrip_fit: FitResult,
    skipped: list[SkipRecord],
) -> None:
    lines = ["# assay — round-1 validation (V1–V4)", ""]

    v1 = report.validate_v1_clustering(main_fit)
    lines.append("## V1 — in-rank clustering")
    lines.append("")
    lines.append(
        "Target: the middle 80% of fit-population spells within ±⅓ rank-equivalent of budget."
    )
    lines.append("")
    lines.append(f"- n = {v1.n}")
    lines.append(f"- share within ±⅓ rank: **{v1.share_within_third_rank:.1%}**")
    lines.append(
        f"- p10 / p90 rank-equivalent residual: {v1.p10_rank_equiv:+.2f} / {v1.p90_rank_equiv:+.2f}"
    )
    lines.append(f"- **{'PASS' if v1.passed else 'FAIL'}** (target ≥80% within ±⅓ rank)")
    lines.append("")

    v2 = report.validate_v2_heighten(main_rows, main_fit)
    lines.append("## V2 — heighten-projection consistency (held out of the fit)")
    lines.append("")
    lines.append(f"- projections computed: {len(v2.projections)}")
    lines.append(f"- mean |residual| (rank-equivalent): {v2.mean_abs_residual_rank_equiv:.2f}")
    if v2.fireball_projection:
        p = v2.fireball_projection
        lines.append(
            f"- Fireball rank {p.base_rank}→{p.target_rank}: projected EV {p.projected_ev:.1f} "
            f"(8d6=28 expected) vs. fitted rank-{p.target_rank} budget {p.predicted_ev:.1f} "
            f"(residual {p.residual_rank_equiv:+.2f} ranks)"
        )
    else:
        lines.append(
            "- Fireball rank-3→4 projection not available (check fit population / rank coverage)."
        )
    lines.append("")

    v3 = report.validate_v3_outliers(main_fit, strong=report.KNOWN_STRONG, weak=report.KNOWN_WEAK)
    v3_cantrip = report.validate_v3_outliers(
        cantrip_fit,
        strong=report.KNOWN_STRONG_CANTRIP,
        weak=report.KNOWN_WEAK_CANTRIP,
        use_raw_residual=True,
    )
    lines.append("## V3 — known-outlier sanity")
    lines.append("")
    lines.append("Non-cantrip rows: residual in rank-equivalents. Cantrip rows (Electric Arc,")
    lines.append("Acid Splash — no rank ladder to divide by): raw log(EV) residual, sign only.")
    lines.append("")
    lines.append("| Spell | Expected | Found | Residual | Correct side |")
    lines.append("|---|---|---|---|---|")
    for c in (*v3.checks, *v3_cantrip.checks):
        r = f"{c.residual_rank_equiv:+.3f}" if c.residual_rank_equiv is not None else "—"
        side = "—" if c.correct_side is None else ("yes" if c.correct_side else "**NO**")
        lines.append(f"| {c.name} | {c.expected} | {c.found} | {r} | {side} |")
    lines.append("")
    lines.append(f"**{'PASS' if v3.all_correct and v3_cantrip.all_correct else 'FAIL'}**")
    lines.append("")

    v4 = report.validate_v4_anchors(main_fit)
    lines.append("## V4 — anchor recovery (fitted ladder vs. community 7×rank / GM Core)")
    lines.append("")
    lines.append("| Rank | Fitted EV | Community 7×rank | Δ vs community | GM Core anchor |")
    lines.append("|---|---|---|---|---|")
    for row in v4:
        gm = f"{row.gm_core:.0f}" if row.gm_core is not None else "—"
        lines.append(
            f"| {row.rank} | {row.fitted_ev:.2f} | {row.community_7x:.0f} | "
            f"{row.delta_vs_community_pct:+.1f}% | {gm} |"
        )
    lines.append("")

    lines.append("## Skip ledger summary")
    lines.append("")
    from collections import Counter

    reasons = Counter(s.reason for s in skipped)
    lines.append(f"Total skipped (all main-slot spells, any reason): {len(skipped)}")
    lines.append("")
    lines.append("| Reason | Count |")
    lines.append("|---|---|")
    for reason, count in reasons.most_common():
        lines.append(f"| {reason} | {count} |")
    lines.append("")

    VALIDATION_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def cmd_score(args: argparse.Namespace) -> None:
    with _tracer.start_as_current_span("assay.score") as span:
        spell_path = Path(args.spell)
        data = load_spell_json(spell_path)
        result = extract_spell(data, str(spell_path))
        if isinstance(result, SkipRecord):
            print(f"assay score: {result.name} could not be scored — {result.reason}")
            span.set_attribute("assay.score.skipped", True)
            return

        if not FITTED_PARAMS_PATH.exists():
            raise SystemExit(
                f"assay score: no fitted params at {FITTED_PARAMS_PATH} — run `assay fit` first."
            )
        params = json.loads(FITTED_PARAMS_PATH.read_text(encoding="utf-8"))
        key = "cantrip" if result.is_cantrip else "main"
        sub = params[key]
        fit = FitResult(
            coefficients=sub["coefficients"],
            columns=sub["columns"],
            residuals={},
            fitted={},
            actual={},
            spell_rank={},
            r_squared=sub["r_squared"],
            n_obs=sub["n_obs"],
            n_params=sub["n_params"],
            rank_slope=sub["rank_slope"],
            rank_slopes={int(r): v for r, v in sub["rank_slopes"].items()},
        )
        predicted_log = predict_log_ev(result, fit, include_rank_ladder=not result.is_cantrip)
        predicted_ev = math.exp(predicted_log)
        actual_log = math.log(result.ev)
        residual = actual_log - predicted_log
        local_slope = fit.rank_slopes.get(result.rank) or fit.rank_slope
        rank_equiv = residual / local_slope if local_slope else float("nan")

        verdict = "in band"
        if not math.isnan(rank_equiv):
            if rank_equiv > 1 / 3:
                verdict = f"{rank_equiv:+.2f} ranks HOT"
            elif rank_equiv < -1 / 3:
                verdict = f"{rank_equiv:+.2f} ranks COLD"

        span.set_attribute("assay.score.spell", result.name)
        span.set_attribute("assay.score.predicted_ev", predicted_ev)
        span.set_attribute("assay.score.actual_ev", result.ev)

        cantrip_note = ", cantrip" if result.is_cantrip else ""
        print(f"assay score: {result.name} (rank {result.rank}{cantrip_note})")
        print(f"  actual EV:    {result.ev:.2f}")
        print(f"  predicted EV: {predicted_ev:.2f}")
        print(f"  verdict:      {verdict}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="assay", description="PF2e homebrew spell power scoring (0030 round 1)."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_extract = sub.add_parser("extract", help="extract the features table -> out/features.json")
    p_extract.add_argument(
        "--data-root", default=None, help="override the codex data root (else config.kdl)"
    )
    p_extract.set_defaults(func=cmd_extract)

    p_fit = sub.add_parser("fit", help="extract + fit -> results/{fitted-params.json,*.md}")
    p_fit.add_argument(
        "--data-root", default=None, help="override the codex data root (else config.kdl)"
    )
    p_fit.set_defaults(func=cmd_fit)

    p_score = sub.add_parser("score", help="score one homebrew spell JSON against the fitted model")
    p_score.add_argument("--spell", required=True, help="path to a Foundry-shaped spell JSON")
    p_score.set_defaults(func=cmd_score)

    return parser


def main() -> None:
    init_telemetry("astra.assay")
    try:
        parser = build_parser()
        args = parser.parse_args()
        try:
            args.func(args)
        except SnapshotNotFoundError as e:
            raise SystemExit(str(e)) from e
    finally:
        shutdown()
