// Generic build-time content pipeline — the reusable spine of the strider
// frontend template (build-time markdown → typed generated TS modules; the
// runtime app imports those, never the filesystem). An app supplies its own
// domain parsing/emit via content sources; this module owns the primitives
// (markdown→HTML, frontmatter, content hashing, module emit) and the runner.
//
// fs/remark/gray-matter live here and stay build-time only — never import this
// from runtime/app code that ships to the client.

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { remark } from "remark";
import remarkHtml from "remark-html";

export const AUTOGEN_HEADER = "// AUTO-GENERATED by @astra/content-build. Do not edit.\n";

/** Markdown → trimmed HTML (remark + remark-html). */
export async function markdownToHtml(md: string): Promise<string> {
  const result = await remark().use(remarkHtml).process(md);
  return result.toString().trim();
}

/** Split YAML frontmatter from body (gray-matter). */
export function parseFrontmatter(raw: string): {
  data: Record<string, unknown>;
  content: string;
} {
  const { data, content } = matter(raw);
  return { data: data as Record<string, unknown>, content };
}

/**
 * Absolute paths of files with the given extension (e.g. `".md"`, `".kdl"`) in
 * `dir`, excluding the given basenames. The extension is matched verbatim, so
 * pass it with the leading dot.
 */
export function listFilesWithExtension(
  dir: string,
  ext: string,
  exclude: ReadonlyArray<string> = [],
): string[] {
  if (!fs.existsSync(dir)) return [];
  const skip = new Set(exclude);
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(ext) && !skip.has(f))
    .map((f) => path.join(dir, f));
}

/** Absolute paths of `*.md` files in `dir`, excluding the given basenames. */
export function listMarkdownFiles(dir: string, exclude: ReadonlyArray<string> = []): string[] {
  return listFilesWithExtension(dir, ".md", exclude);
}

/**
 * Pure, order-independent content digest: sorts by relative path, then hashes
 * (rel, bytes) pairs with NUL separators. Useful for cache-busting / build
 * provenance; unit-testable without touching the filesystem.
 */
export function hashFiles(files: ReadonlyArray<{ rel: string; bytes: Buffer | string }>): string {
  const sorted = [...files].sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
  const hash = crypto.createHash("sha256");
  for (const { rel, bytes } of sorted) {
    hash.update(rel);
    hash.update("\0");
    hash.update(bytes);
    hash.update("\0");
  }
  return hash.digest("hex").slice(0, 16);
}

/** Write a generated TS module (AUTOGEN header prepended) into `outDir`. */
export function emitModule(outDir: string, filename: string, body: string): void {
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, filename), AUTOGEN_HEADER + body);
}

/** Emit the `.gitignore` that keeps generated output out of git. */
export function emitGitignore(outDir: string): void {
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, ".gitignore"), "*\n!.gitignore\n");
}

/**
 * A content source: a named build step that reads its content dir and emits one
 * or more generated modules (via {@link emitModule}). Apps declare their domain
 * parsing here; the registry just sequences + logs them.
 */
export interface ContentSource {
  name: string;
  build: () => Promise<string> | string; // returns a short summary for the log
}

export function defineContentSource(source: ContentSource): ContentSource {
  return source;
}

/**
 * Run content sources into `outDir`: ensure the dir, write the gitignore, then
 * run each source's build() in order. Returns the per-source summaries.
 */
export async function buildContent(
  outDir: string,
  sources: ReadonlyArray<ContentSource>,
): Promise<string[]> {
  fs.mkdirSync(outDir, { recursive: true });
  emitGitignore(outDir);
  const summaries: string[] = [];
  for (const source of sources) {
    summaries.push(await source.build());
  }
  return summaries;
}
