anthropic_api_key: ENC[AES256_GCM,data:+X/S8uOwzGO+6w==,iv:KiFHkUw46s2JU2ZzBAsZsLU1W/CIrZRI7jJoGGWMDX4=,tag:umyqynRxrlJTJxAa6Uqh4A==,type:str]
groq_api_key: ENC[AES256_GCM,data:jqAgr4klLZxKgA==,iv:gw6iw9kShBO32nSeaZeXRlOMKkuqtMZiHAZtM5tV6jg=,tag:IIVCv/BPQ4GZz+h2gY9Ilw==,type:str]
dice_feed_url: ENC[AES256_GCM,data:EABO1w4iN39vfA==,iv:e9tz9XRrhXfsU/2AQR04w4AW5LVL7WxyQ6TdX4Ver34=,tag:j24d3sDS33+Y6NrtDgrEcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbmVmZ1BIK2dSemUwNlVn
            UjRnY0ZubXNMdnp6Y0FUbUxxQzBhaklpVFd3CmQwd3JoMjVBbzNyTk1jMHJmSXpu
            S0NxY2ZzUGRxY1VGVFU0c1JJRWlvWmsKLS0tIGlIdDdkYTBzcm9zSFlYNU1aTUQr
            dDFXVU1ibUpXRlJHQklXZzlHc2JuRk0Ka0+FFsZOntjh6eERgjQJaHfjkMmyYlh7
            SlfK0ebl+fG1pydAp+xKtEqKYccUkDjJRCUpkuL7Q/3PYxqLXc6yCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q4l83znay8mrnlsnpv3anh0kkmj97vhx4fyn379tkalemxz0cyls5qw9s4
    lastmodified: "2026-06-19T18:39:17Z"
    mac: ENC[AES256_GCM,data:D3HvucF+7ywuRw/ccxi4T2ChvEwXjIW1e2hibhU9cgvS3lpYk07bXP/3EAHNp/OdcuznFVbWNmru30W77jUkwPqGrF1/PztM6RUfJRCxBCkbefLpdKc5IUbmU4vMb1TUgHzjP42L40yhq50VtmglgG4MJ90B+ftoHsiZ+ECs5hw=,iv:EiDUQzt3MkSDlmiVTInK+OWDvv4R2hDU6aMhDeDSsSQ=,tag:dGimU70jFOwaUpV/rzNj7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
