/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as ChronicleIndexRouteImport } from './routes/chronicle/index'
import { Route as TagsSplatRouteImport } from './routes/tags/$'
import { Route as ChronicleShowRouteImport } from './routes/chronicle/$show'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleIndexRoute = ChronicleIndexRouteImport.update({
  id: '/chronicle/',
  path: '/chronicle/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSplatRoute = TagsSplatRouteImport.update({
  id: '/tags/$',
  path: '/tags/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleShowRoute = ChronicleShowRouteImport.update({
  id: '/chronicle/$show',
  path: '/chronicle/$show',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chronicle/$show': typeof ChronicleShowRoute
  '/tags/$': typeof TagsSplatRoute
  '/chronicle/': typeof ChronicleIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chronicle/$show': typeof ChronicleShowRoute
  '/tags/$': typeof TagsSplatRoute
  '/chronicle': typeof ChronicleIndexRoute
  '/tags': typeof TagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/chronicle/$show': typeof ChronicleShowRoute
  '/tags/$': typeof TagsSplatRoute
  '/chronicle/': typeof ChronicleIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/chronicle/$show'
    | '/tags/$'
    | '/chronicle/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/chronicle/$show' | '/tags/$' | '/chronicle' | '/tags'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/chronicle/$show'
    | '/tags/$'
    | '/chronicle/'
    | '/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ChronicleShowRoute: typeof ChronicleShowRoute
  TagsSplatRoute: typeof TagsSplatRoute
  ChronicleIndexRoute: typeof ChronicleIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle/': {
      id: '/chronicle/'
      path: '/chronicle'
      fullPath: '/chronicle/'
      preLoaderRoute: typeof ChronicleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$': {
      id: '/tags/$'
      path: '/tags/$'
      fullPath: '/tags/$'
      preLoaderRoute: typeof TagsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle/$show': {
      id: '/chronicle/$show'
      path: '/chronicle/$show'
      fullPath: '/chronicle/$show'
      preLoaderRoute: typeof ChronicleShowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ChronicleShowRoute: ChronicleShowRoute,
  TagsSplatRoute: TagsSplatRoute,
  ChronicleIndexRoute: ChronicleIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
